[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
ripemd = "0.1.3"
ripemd160 = "0.10.0"
serde = "1.0.152"
serde_json = "1.0.92"
