name: Build and deploy container app to Azure Web App - nikiesboldi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        cargo test

  build:
    needs: test
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1 
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rust_webserver:latest

  deploy-uat:
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Azure UAT
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rust-webserver'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_TEST }}
        images: '${{ secrets.DOCKER_HUB_USERNAME }}/rust_webserver:latest'

  deploy:
    needs: build
    runs-on: 'ubuntu-latest'
    environment: Deployment
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nikiesboldi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_741E96E134F24666A755851BAD24AE96 }}
        images: '${{ secrets.DOCKER_HUB_USERNAME }}/rust_webserver:latest'