name: Build + Test

# on push to master, run the build and test jobs
on:
    push:
        branches:
        - master

jobs:
    build_job:
        name: build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
        uses: actions/checkout@v2
        - name: Build
        run: |
            echo "Building the app"
            echo "Build complete"

on:
    workflow_dispatch:

jobs:

    sudo docker stop webserver
    sudo docker rm webserver
    sudo docker build -t webserver .
    sudo docker run -dp 80:7878 --restart unless-stopped webserver