name: Build + Test

# on push to master, run the build and test jobs
on:
    push:
        branches:
        - master

jobs:
    build_job:
        name: build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
        uses: actions/checkout@v2
        - name: Build
        run: |
            echo "Building the app"
            echo "Build complete"
